/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class burner_EvalJNI */

#ifndef _Included_burner_EvalJNI
#define _Included_burner_EvalJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     burner_EvalJNI
 * Method:    loadModel
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_burner_EvalJNI_loadModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     burner_EvalJNI
 * Method:    evaluate
 * Signature: (J[JI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_burner_EvalJNI_evaluate
  (JNIEnv *, jobject, jlong, jlongArray, jint);

#ifdef __cplusplus
}
#endif
#endif
